#!/bin/bash

ASTAR="../../bin/astar.x"

for item in $(ls)
do
    if [[ -d "${item}" && ! -L "${item}" ]]; then
        cd ${item}
        ${ASTAR} a.inp > a.sol
        cmp a.sol a.sol.ref
        if [ $? -eq 0 ]; then
            echo $item OK
        else
            echo $item FAILED
        fi
        cd ..
    fi
done


